server:
  port: 8084
  servlet:
    session:
      timeout: 1800s
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin_ht?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: bug140128code
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  thymeleaf:
    encoding: utf-8
    cache: false
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  aop:
    proxy-target-class: true
  resources:
    static-locations: classpath:/templates/,classpath:/resources/,classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: com.sc.adminht.entity.*

logging:
  config: classpath:logback-config.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


